//
// AuthenticationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AuthenticationResponse: Codable { 


    public var authToken: String

    public init(authToken: String) {
        self.authToken = authToken
    }

}
