//
// AuthenticationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AuthenticationRequest: Codable { 


    public var apiKey: String
	public var target: CfTarget

	public init(apiKey: String, target: CfTarget) {
        self.apiKey = apiKey
		self.target = target
    }

}
