// Extensions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension HTTPURLResponse {
    var isStatusCodeSuccessful: Bool {
        return Array(200 ..< 300).contains(statusCode)
    }
}


