//
// AuthenticationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AuthenticationRequest: Codable { 


    public var apiKey: String

    public init(apiKey: String) {
        self.apiKey = apiKey
    }

}
